### PR TITLE
Git week1

### PR DESCRIPTION
**Pull request by Hanouj**

### CODE REVIEW

**Comment by mariagroves** [comment]
Nice work! 💪 Next time, please make sure that your commit messages are descriptive enough and are understandable for other people. Rather than using the name of the file as the commit message you could say something like "added countries I have visited". 

Now could you please add one more country name to the file `countries.txt`, add, commit and push it. This is your chance to practice writing a more descriptive commit message! After you have pushed you should see the new commit show up in this PR.

**Comment by Hanouj** [comment]
okay so the commit doesn't have to contain  the same file name ? and I can give the commit the name I want `?

**Comment by mariagroves** [comment]
> okay so the commit doesn't have to contain the same file name ? and I can give the commit the name I want `? and my index files that I had in git/week1 all disappeared what should I do ? do I create the same files and give it the same name and just add to it ?

1. The commit message should describe what you did - it should not be the file name.
2. Can you check that you are on the `git-week1` branch? The files will be gone if you leave that branch. So if you are on another branch do `git checkout git-week1` and the files should be there again.

**Comment by Hanouj** [comment]
thank you this was very clarifying

**Pull request merged**
